language: C
compiler:
    - gcc
    - clang
    - i686-w64-mingw32-gcc

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -q -y gcc-mingw-w64-i686 wine wine32 wine64 libwine libwine:i386

script: ./travis-build.sh


